kind: pipeline
name: msn-server
type: docker

steps:
  - name: Build Docker Image
    image: docker:dind
    volumes:
    - name: dockersock
      path: /var/run/docker.sock
    commands:
    - docker build . -t msn-server:latest
  - name: Start Container
    image: docker:dind
    volumes:
    - name: dockersock
      path: /var/run/docker.sock
    commands:
    - docker stop msn-server || true
    - docker rm msn-server || true
    - docker run --name msn-server --network=bridge -p 8084:8000 -d msn-server:latest


volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock